### ISSUE TITLE
Database:  only one peripheral per game allowed

### ISSUE THREAD

**Issue by keithbowes** [libretro/nestopia#11]
I have Super Mario Bros/Duck Hunt/World Class Track Meet and the Zapper doesn't work for Duck Hunt.  I've tracked down the problem in the NstDatabase.xml file (with an older version of the core, before NstDatabase.xml got baked-in):
```xml
<peripherals>
  <device type="zapper"/>
  <device type="powerpad"/>
</peripherals>
```

The second device overrides the first, so the Zapper doesn't work.  However, if I delete the powerpad device (logical, as I don't have a USB PowerPad) or invert the order, the Zapper works fine.

However, Nestopia should support both (and other peripherals, if they exist) simultaneously.

**Comment by JukePlz** [comment]
Having an option to swap the devices in the UI seems like it would work, but I'm against the idea of supporting them both "simultaneously". The original console only has ONE expansion port, receiving the inputs from multiple devices could have unintendeed consequences.

**Comment by keithbowes** [comment]
Yeah, FCEUmm's system is more like the original console, where you can specify the input device in port 2 at run-time (or in per-game overrides, if that's your thing), but the point is that Nestopia is broken like this, especially in newer versions with the ill-advised decision to bake-in NstDatabase.xml (where playing Duck Hunt in Super Mario Bros/Duck Hunt/World Class Track Meet just doesn't work).
