### ISSUE TITLE
Show message when flipping and swapping disks

### ISSUE THREAD

**Issue by arromdee** [libretro/nestopia#18]
Flipping and swapping FDS disks is confusing because there is no feedback whatsoever.  As a result, the user is required to remember what the current disk side is.  And woe be it if your joystick is flaky and registers two button presses--you'll just get a disk error.  (Yes, this happened to me.)

Suggestions:
1) Two button presses less than some fraction of a second apart should not flip/swap the disk twice--the second one should be ignored.
2) Flipping or swapping the disk ought to display a message in the GUI saying that it flipped or swapped, and what the current side and disk are.

**Comment by arromdee** [comment]
Is this fixed or is it just closed?

**Comment by SigmaVirus** [comment]
Well through some investigation I found a commit (Display FDS info on screen) that's dated 17 Feb 2015:
https://github.com/libretro/nestopia/commit/3af0c481d10cf1a37223091723b29a07447866f6

However, I don't see any text on screen whatsoever when I change side of the Disk.
As for changing Disk side in general, one solid push of the L button changes the side easily (I don't know if this always was the case)

One accidental slip of the button though and it's Disk Error time. Thank god for backups!

What I would like to see though is a solution similar to puNES, where Alt+E ejects and inserts a Disk and Alt+S changes the side of a Disk.
That way you ain't relying on a simple button press and the chances for Disk errors to happen are far less likely to happen.
