### ISSUE TITLE
load ROMs not in db

### ISSUE THREAD

**Issue by eadmaster** [libretro/nestopia#19]
this is an annoying behavior Nestopia has compared to other emus like [fceumm](https://github.com/libretro/libretro-fceumm): if a ROM is missing in the `NstDatabase.xml` it won't load at all.

I know the correct way to "fix" this is by adding a new entry in the db, however this is still an annoying process to repeat everytime you want to try a new patch.

As alternative, [NES ROMs carry infos like the mapper inside the iNes header](https://bheisler.github.io/post/nes-rom-parser-with-nom/#the-ines-header), so maybe we can fallback to that if there is no match with the db?

**Comment by keithbowes** [comment]
Really?  Back when NstDatabase.xml wasn't baked-in, games would work with it in your system directory, but it sometimes would pick the wrong peripherals (the code always defaulted to PAD1 and PAD2 for ports 1 and 2 when the database couldn't be found).

**Comment by eadmaster** [comment]
> Really? Back when NstDatabase.xml wasn't baked-in, games would work with it in your system directory, but it sometimes would pick the wrong peripherals (the code always defaulted to PAD1 and PAD2 for ports 1 and 2 when the database couldn't be found).

I think this is still better than not booting at all, since it can be  fixed with a bit of guessing via the RA menus...

**Comment by carmiker** [comment]
Games not in the DB will load just fine as long as they do not require any special information beyond what is in the header to be loaded correctly. Often these problems can be fixed by just modifying the header.
