### ISSUE TITLE
Info file fails checksum when using makepkg

### ISSUE THREAD

**Issue by css459** [libretro/nestopia#21]
When using the latest Arch packages and linux kernel, I run into an error in which the checkusm for the info file is failing. I cloned the repo and ran `makepkg -s` and encountered this output

```
==> Making package: libretro-nestopia-git r612.7c8d9d9-1 (Tue Mar  1 23:02:58 EST 2016)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Cloning libretro-nestopia git repo...
Cloning into bare repository '/home/cole/Documents/Retroarch/Cores/libretro-nestopia-git/libretro-nestopia'...
remote: Counting objects: 5065, done.
remote: Total 5065 (delta 0), reused 0 (delta 0), pack-reused 5065
Receiving objects: 100% (5065/5065), 4.23 MiB | 458.00 KiB/s, done.
Resolving deltas: 100% (3462/3462), done.
Checking connectivity... done.
  -> Downloading nestopia_libretro.info...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   630  100   630    0     0   3454      0 --:--:-- --:--:-- --:--:--  3461
==> Validating source files with sha256sums...
    libretro-nestopia ... Skipped
    nestopia_libretro.info ... FAILED
==> ERROR: One or more files did not pass the validity check!
```
As you can see, the package could not be made properly because of this. This is on a fresh clone of the package that I used only 10 mintues prior to writing this issue report.

Thanks!

**Comment by Enverex** [comment]
That's nothing to do with libretro or Nestopia (and nothing they can do about this). Packages are often maintained by people with nothing to do with the upstream software.

You need to report this to the person maintaining the AUR package for Arch (which I've already done, FYI).
