### ISSUE TITLE
Can't open Gryzor rom

### ISSUE THREAD

**Issue by GeneralFailer** [libretro/nestopia#23]
I'm using version from repos on Arch Linux and Retroarch exits to desktop every time I try to open Gryzor rom. Normal Contra opens fine. The log is in attachment.
[log.txt](https://github.com/libretro/nestopia/files/253611/log.txt)

**Comment by fr500** [comment]
RetroArch [libretro INFO] :: NstDatabase.xml path: /mnt/files/Vidya roms//NstDatabase.xml
RetroArch [libretro WARN] :: NstDatabase.xml required to detect region and some mappers.

**Comment by rdanbrook** [comment]
Yes, just throw NstDatabase.xml into your system directory. Gryzor is also a hack, you may want to use the proper Japanese Contra rom.

**Comment by GeneralFailer** [comment]
@rdanbrook, according to Wikipedia, it was only released as Contra in the US.

**Comment by twinaphex** [comment]
Gryzor was for the MSX or some similar system I believe. On Famicom it was released as Contra in Japan, Probotector in Europe.

**Comment by GeneralFailer** [comment]
Well, either you or [the Wikipedia list](https://en.wikipedia.org/wiki/List_of_Family_Computer_games) are incorrect then.

**Comment by GeneralFailer** [comment]
Weird, most of the biggest romsites only refer to the FC version as Gryzor. Sorry for doubting you, I guess.
