### ISSUE TITLE
Option to hide crosshairs for lightgun games

### ISSUE THREAD

**Issue by Bitwolfies** [libretro/nestopia#24]
This option exists in standalone, and now that things like the sniden lightgun exist, being able to hide the crosshair would be great.

**Comment by keithbowes** [comment]
I was considering doing that when I updated the core to use the new lightgun API, but I couldn't imagine why on Earth anyone would actually want to hide the crosshair.  I'll look into it.

**Comment by Bitwolfies** [comment]
Ahh the march of time
