### ISSUE TITLE
Update to 1.51.0

### ISSUE THREAD

**Issue by keithbowes** [libretro/nestopia#26]
I'm not sure the best way to do this:
1. Cherry pick the relevant changes from upstream.
2. Rebase to use upstream.
3. Create a submodule for use of Rupert Carmichael's backend.
4. Create a submodule but also allow using the existing backend, sort like snes9x2005 does for the different APUs.

**Comment by rdanbrook** [comment]
Hey @keithbowes, I put in a pull request that does things the way I think it should be done: https://github.com/libretro/nestopia/pull/27

That doesn't revert the database being baked in, but I think that should be done too.
