### ISSUE TITLE
Zoda's Revenge: StarTropics II Doesn't Work

### ISSUE THREAD

**Issue by bleakassassin** [libretro/nestopia#29]
There are three issues that I can find. Since I can't progress in the game, I don't know if there's others beyond what I've mentioned.

1) No sound plays.
2) Purple rectangles fill up each empty file name as opposed to black space.
3) It is impossible to create a save file and start the game. Attempting to register a file results in the game sending you back to the file select screen without registering the file.
4) (only able if you import a save from another emulator) Many screen transitions cause the game to lock up on a black screen. Since there's no sound to begin with, I don't know if the game is crashing or just failing to render the next area.

The log file doesn't reveal anything out of the ordinary. Both the FCEUmm Libretro core and Nestopia UE standalone work without any problems.

**Comment by hizzlekizzle** [comment]
Works fine here. Do you have NstDatabase.xml in your system/BIOS directory?

**Comment by bleakassassin** [comment]
Weird. I could have sworn that it was already there before. That was indeed the problem.

I'm confused as to why RetroArch doesn't come with it beforehand. It seems there's nothing about the database file that's proprietary or copyrighted, so it seems odd to have that as an extra step.
