### ISSUE TITLE
FDS change disk don't work

### ISSUE THREAD

**Issue by Rocklima2** [libretro/nestopia#33]
Hi i try start game .fds, but change disk Button not working in last version of core , tested on lakka version rpi2 and Windows version retroarch.

**Comment by Rocklima2** [comment]
@rdanbrook your version of core this work?please

**Comment by Rocklima2** [comment]
I try test last release of core and problem is present, wait message eternal on all games not showing message change disk

**Comment by SigmaVirus** [comment]
I can change disk sides just fine, my change disk button is mapped to q in RetroArch.
I'm currently using the latest Nestopia core along with an older version of RetroArch through the RAEM front-end.

RetroArch is great but things sometimes tend to be up and down and very sensitive to changes.
One moment everything works, and the next things can be broken.

I'm more then willingly to try a newer version of RetroArch when I get home from work to see if what you're describing still occurs.

**Comment by SigmaVirus** [comment]
Tried with latest core from 10th of September and a RetroArch build from 18th of September on Windows 10 and I could change disk side just fine using the q key.

I can't reproduce this at all.

**Comment by Rocklima2** [comment]
@SigmaVirus thanks i try re-dump files but prior version i have played all games, i try use keyboard and joypad for test.

**Comment by SigmaVirus** [comment]
I've tested the updated core from yesterday (2016-09-24) and it's still working as expected changing sides.

**Comment by Rocklima2** [comment]
I use option retroarch Core update , i dont try download cores (2016-09-24), but i try for test, thks my games freeze loading message before change side disk.

**Comment by SigmaVirus** [comment]
@Rocklima2 
Here's what you could try:

1. Make a backup of your current RetroArch setup
2. Copy the backup somewhere safe
3. Delete all your RetroArch configuration files
4. Now fresh, load your Nestopia core and the ROM you want to test

Now 2 things could happen here, either pressing q to change side of the disk will work or it doesn't.
If it still not working then it could mean that the game dumps is bad and that's why you having all these issues.

**Comment by hizzlekizzle** [comment]
Also make sure you have a copy of the NstDatabase.xml in your 'system' directory. Nestopia can act strangely without it sometimes.

**Comment by Rocklima2** [comment]
Thanks for all @SigmaVirus  and @hizzlekizzle , NstDatabase.xml solved my problem, all rom working perfect. I close this issue.

**Comment by SigmaVirus** [comment]
@Rocklima2 OK that sounds perfect!

@rdanbrook 

Just a thought here, would it be possible to bake in the NstDatabase.xml to the core? Kinda like GLupeN64 baked in the mupen64plus.ini file.

Maybe even have a core option for it? Like "Use internal NstDatabase.xml" and it's using the one baked in and "Use external NstDatabase.xml" and it's using the one found in the system folder.

**Comment by rdanbrook** [comment]
I'm definitely open to that. How is it done in GLupeN64? Do they just turn the .ini file into a gigantic string? If someone can point me to that I'd love to see it.

**Comment by hizzlekizzle** [comment]
I asked loganmc10 about it in IRC and this was his reply:
12:29 PM L<loganmc10> sure ,if you look here
12:29 PM L<loganmc10> https://github.com/loganmc10/GLupeN64/tree/master/custom/mupen64plus-core/main
12:29 PM L<loganmc10> here is a mupen64plus.ini.h, that is the .ini file converted to a char[]
12:30 PM L<loganmc10> there is*
12:30 PM L<loganmc10> so basically mupen64plus.ini becomes a char[] called inifile
12:31 PM L<loganmc10> then if you look in the rom.c file in that same folder
12:31 PM L<loganmc10> it includes that .h file and uses strtok to read through inifile
12:32 PM L<loganmc10> I tried to do it in a way that is as similar to how it works in mupen64plus as possible, so it uses strtok to read through that char[] like it would a file

**Comment by SigmaVirus** [comment]
Absolutely brilliant answer from loganmc10 and a big thank you @hizzlekizzle for asking the question. From what I'm reading, baking in NstDatabase.xml to the core doesn't seem to be impossible at all.

It would be a big relief if it was baked in and it would be at least one less file to worry about.

And having a core option to choose whether you want to use the internal one or an external one from the system folder (for those who want to make custom changes to it) would be great too.

**Comment by rdanbrook** [comment]
OK, so it looks like it's a giant string. It shouldn't be hard to do it the same way in the Nestopia codebase.

**Comment by SigmaVirus** [comment]
@rdanbrook Any update regarding a possible NstDatabase.xml integration?

**Comment by rdanbrook** [comment]
I'll be able to do it the next time I have a bit of free time. Possibly over the weekend.

**Comment by SigmaVirus** [comment]
Sweet!
I know just the game from my collection that I'm gonna try this out with once it's done, Wai Wai World.
That game needs the NstDatabase.xml for sure.

**Comment by SigmaVirus** [comment]
@rdanbrook 

There have been a massive amount of weekends passing by since September/October 2016, do you have any interest in baking in the NstDatabase.xml to the Nestopia core?

**Comment by rdanbrook** [comment]
I can't figure it out. If you can, let me know. Anyone!

**Comment by rzumer** [comment]
Can you move this to a separate issue? It seems unrelated to the initial problem.
