### ISSUE TITLE
[Android] Nestopia crashes if built with Clang

### ISSUE THREAD

**Issue by sergiobenrocha2** [libretro/nestopia#35]
It'll crash if using clang to build. GCC works. Thanks radius

https://github.com/rdanbrook/nestopia/issues/208

**Comment by fr500** [comment]
To elaborate, if was crashing when built with r13b, it works with r10e
From my understanding it uses CLANG for ARM-v7a
https://developer.android.com/ndk/guides/standalone_toolchain.html

> By default, an ARM Clang standalone toolchain will target the armeabi-v7a ABI. GCC will target armeabi. Either can be controlled by passing the appropriate -march flag, and Clang can also be controlled with -target.

**Comment by rdanbrook** [comment]
Seems to be fixed.
