### ISSUE TITLE
Moero! Pro Yakyuu (JPN) (Jaleco Voice Samples Loading?)

### ISSUE THREAD

**Issue by KMFDManic** [libretro/nestopia#36]
@rdanbrook its been awhile!  Hope all is well.  You previously added "THIS" commit.  But, it was kind of lost when the "hack" occurred on libretro awhile back.  I was personally trying to get it up and running on my end, as far as running the samples.  Not sure if it is fresh enough in your memory to remember anything about it?  So far, I attempted to have etc/libretro/system/nestopia/samples/samples here in zip and in folder format, and load of the games that SHOULD trigger the samples, to no avail.  Any input on this?

https://notabug.org/0ldsk00l/nestopia/commit/441a13a7544ec8807f3ede550f6db2326c2566dc

This video shows the before and after, WITH how the samples would usually be.  I am hoping to be able to have success in running them, as well!

https://www.youtube.com/watch?v=JQAy6_ZLE3c

**Comment by carmiker** [comment]
The samples should be placed in `~/.config/retroarch/system/nestopia/samples/`. They need to be extracted into a subdirectory named after the zip, for example `moepro` for `moepro.zip`.
