### ISSUE TITLE
Game Crashing Nestopia

### ISSUE THREAD

**Issue by Flashfire42** [libretro/nestopia#37]
When attempting to launch Alfombra Magica, La (Spain) (Rev 1) (Gluk Video) (Unl) from the No-Intro set it simply fails to load content. Wondering if this can be remedied?

**Comment by hizzlekizzle** [comment]
Does your ROM have a header? I believe unheadered ROMs don't work (unless you have the NstDatabase.xml in 'system'?)

**Comment by Flashfire42** [comment]
This is from the no-intro sets it should have a header

**Comment by hizzlekizzle** [comment]
I believe No-Intro stopped including headers in their NES sets awhile back.

**Comment by Flashfire42** [comment]
as it turns out this particular ROM does not have a header. I just checked it.
