### ISSUE TITLE
[win_x64]Wai Wai World (1 and 2) will not run without NstDatabase.xml - broken soft/hard IPS patch

### ISSUE THREAD

**Issue by retro-wertz** [libretro/nestopia#39]
wai wai world will not load if NstDatabase.xml is not in <system> directory. also, breaks IPS soft or hard patch
ROM / ISO Information:
File: Wai Wai World (J) [!].nes
Length: 262160 Bytes (2 Mbit)
CRC32: B27BCF3D
MD5: 752353CC C6678C72 7926B661 C7AD5E3F
SHA1: D509F4CF 534C3638 A2931456 3E98DE5F 963F8264

IPS patch is from Zynk

**Comment by GeneralFailer** [comment]
Can confirm mapper 23 rom soft patching being broken.  Hard patching probably [isn't supposed to work](https://github.com/rdanbrook/nestopia/issues/7)

**Comment by rdanbrook** [comment]
Set them to submapper 15 and it will work.

**Comment by retro-wertz** [comment]
how do you even do that.....

**Comment by rdanbrook** [comment]
Use this tool: https://github.com/rdanbrook/cirugia

Or use the Windows standalone port and edit the header using that.

**Comment by retro-wertz** [comment]
thanks. that worked, but then it changed crc of rom, its another rom import issue with retroarch since their current database is not updated to use no-intro_nes.xml or headerless-rom hash,might as well have hard-patched rom.

**Comment by GeneralFailer** [comment]
Soft patching still crashes with `Fatal error received in (BPS).` on Akumajou Special though.

**Comment by retro-wertz** [comment]
probably core needs to read rom crc 1st before applying soft-ips? there seems to be no issue with other emu with mapper 23 softpatching.

**Comment by GeneralFailer** [comment]
WWW2's mapper 21 w/ submapper 9 doesn't seem to be supported yet.

**Comment by GeneralFailer** [comment]
I guess this could be reopened since at least half of it is still relevant.

**Comment by retro-wertz** [comment]
request to re-open this issue, as for the moment ability to do soft patching seems to be part-implemented by the core.  currently fceumm does not support soft-patching but a few mods and it is able to use soft-patch especially with mapper23 roms without crash or core not loading or the need to modify header.

ss for getsu fuuma: 
http://imgur.com/hm5WwVl
