### ISSUE TITLE
Turbo buttons please....

### ISSUE THREAD

**Issue by prataczak** [libretro/nestopia#40]
FCEU has turbo keys that you can remap, I'd like to see NEStopia get that also. $50 to the first person that makes this happen. I know that probably sounds a little ridiculous but I love my turbo buttons, and I also happen to prefer NEStopia. Another $50 for anyone who gets turbo remap keys working for Mednafen SuperGrafx + Mednafen PCE Fast. Message here if/when you do it, and I'll personally send you a paypal payment.

**Comment by hizzlekizzle** [comment]
PCE-Fast already has turbo toggles in the core options, which is more appropriate to how the actual controllers handled it than remaps: https://github.com/libretro/beetle-pce-fast-libretro/blob/master/libretro.cpp#L1769

I think it and the SuperGrafx core are similar enough that the same strategy should work there.

**Comment by fr500** [comment]
I think we should remove the turbo buttons from the cores and have something better in the frontend.

**Comment by hizzlekizzle** [comment]
I added them to PCE, but only to buttons I and II, because the PCE controllers have turbo switches on them and the games sometimes leveraged that. I think Wonderswan is in the same boat.

For other cases, where turbo is just a convenience, I agree that handling it in the frontend is sufficient/preferable. Having turbos accessible from the remap menu (i.e., by building them into the core and mapping them to unused buttons) is nice, though.

**Comment by fr500** [comment]
My idea was to have a hotkey that changes the turbo level for a button.
So hotkey + A makes A turbo level 1
hotkey + A again makes it level 2

Maybe 3 levels and then reset to 0

**Comment by prataczak** [comment]
hizzlekizzle, thank you for bringing PCE Fast to my attention. Last time I checked it, there wasn't anything, and I use Super Grafx by default since it plays everything (means one less thing to configure).

I'm a man of my word, but I'll give you half credit for that, since it was already done, so $12.50. If you can get it working for SuperGrafx as well, I'll give you the other $25. You got an email or something, for a donation? I certainly appreciate you adding the turbo keys.

Regarding the hotkey for the frontend - yes, that would absolutely be an incredible addition to RetroArch. But I'm still using the stable version from earlier in the year, because there's a few things that are broke in the latest nighttlies - noteably, the turbo HOLD key in the main input options doesn't save from system to system (e.g. I have L2 set to turbo for NES, but I have to disable it again for PS1, and core overrides will not save from system to system for controls), plus some other annoying stuff.

I figured if we could add turbo remaps to the most commonly turbo-friendly system cores, I wouldn't have to wait another 6 months (or if it ever even happens) for something better to happen within RetroArch. Mainly just systems with 2 buttons. Gameboy could benefit from it. Master System could... but I don't care too much about that to be honest. Sega Genesis, maybe, but then they switched to the 6 button controllers at some point, so I don't know.

Anyways, hizzlekizzle, your toggle solution for TG16 is perfectly acceptable to me, and it is actually very authentic. But if anyone wants to take a stab at getting NEStopia working, that $50 is waiting for you. I'm good for it.

**Comment by prataczak** [comment]
I just tried PCE Fast.

Your solution isn't quite what I thought it was, unless I'm missing something. Is there a way to map that toggle to a button (like I hold R2 and then tab the button or something), or do I have to bring up the menu every time I want to change the turbo settings?

**Comment by prataczak** [comment]
Totally not trying to seem unappreciative, I'm glad you included something in the way of turbo buttons. But for a truly authentic experience, you need to be able to change the settings on the fly, and opening a menu, while better than nothing at all, just doesn't cut it.

**Comment by hizzlekizzle** [comment]
No worries, I don't need any money. Thanks for the offer, though.

**Comment by prataczak** [comment]
The way I figure it, people like you solve problems all the time, for the rest of the community, and for the most part, the community just takes it for granted and complains.

Now here I am, complaining that your original solution "wasn't good enough," so please... I insist. If you find the time to get this done, let me say thanks by rewarding you for your time. Time is the most valuable commodity we have in this life, and what did I ever do to deserve any help from you, when I don't contribute anything?

It's the least I can do. If you solve this dilemma, the entire community benefits with an even more awesome emulation experience.

**Comment by rdanbrook** [comment]
If I add this, and I may, please donate any money to charity.

I agree that this should be a frontend feature. However, in the absence of that I am open to doing it in the libretro core.

**Comment by prataczak** [comment]
Fair enough... but you get to pick the charity. :)

**Comment by fr500** [comment]
We already have a turbo toggle.
The way it works is you press turbo, then the button and the button is in turbo mode till you release it.

It's 100% serviceable the way it is.

**Comment by prataczak** [comment]
I consider that a 'hold,' not a toggle.

That is useful to have also, for schmup games, where you have to charge your shot.

But a true toggle would leave the button in turbo mode, until you press and hold the turbo key and press the button again, which would toggle it to the next setting.

**Comment by retro-wertz** [comment]
this is one of the reasons i use other cores or standalone nestopia, need that dedicated turbo buttons

**Comment by prataczak** [comment]
Yeah it's a real shame that the NEStopia turbo buttons didn't make it into the libretro core. It's very good otherwise, but the lack of the turbo keys does make it very tempting to just go with the standalone.

FCEU is a good emulator, but it's disappointed me many times with lack of compatibility (notably, the Japanese version of Castlevania III).

**Comment by rdanbrook** [comment]
Don't worry, it's coming. We do this as a hobby and sometimes do not have time to implement things immediately.

**Comment by prataczak** [comment]
Awesome, glad to hear it!

**Comment by rdanbrook** [comment]
I implemented it, and also added a core option to control the pulse speed. This is not fine-grained for each button and each pad and simply controls a global pulse speed for all gamepads. It could be expanded in the future if anyone cares, but for now we have basic turbo button support.

Please direct your donations here:
https://donate.childsplaycharity.org/

**Comment by prataczak** [comment]
Thank you sir!

![2016-11-26 2](https://cloud.githubusercontent.com/assets/12243933/20644287/5fff3dc4-b3fd-11e6-9dc9-7e6372f49402.png)

**Comment by prataczak** [comment]
Almost there...

Player 1's turbo keys are activating Player 2's turbo keys, and Player 2's turbo keys are currently not working.

I haven't tested 4 players yet.... when you get this fixed, let me know and I'll try it out with Super Spike V-Ball.

**Comment by rdanbrook** [comment]
Fixed it, it was a stupid typo.

**Comment by prataczak** [comment]
Just tested it again. 2 player Contra is working. Very cool.

4 Player games are still non functional though (Tested with Super Spike V-Ball). None of the players have turbo.

One other issue I just noticed while testing it this time - the new turbo functions you added only work when I manually load the core, and manually load a game. If I try to load a playlist game (doesn't matter if I pre-load the new core first), all the extra numbers (9fe something something) disappear, and it seems that I'm using the previous NEStopia.

**Comment by prataczak** [comment]
Also, if anyone wants to tackle that Mednafen TurboGrafx-16/SuperGrafx stuff, I've still got another $50 waiting to be claimed!

**Comment by rdanbrook** [comment]
I usually test with A Nightmare on Elm Street for anything 4-player, that worked fine for me. Thanks for taking the time to test extensively though. Certain games may react differently to different turbo pulse speeds, by default I chose the one that works best in the Mega Man series.

**Comment by prataczak** [comment]
I have but one gripe/request.

Some people prefer no turbo, and I can already foresee me & a couple of friends geeking out on some NES, and one of them getting angry that there's no way to turn off the turbo buttons to 'play as a purist.'

I personally intend to use it for pretty much every game BUT I do think it would be nice if, in the turbo pulse rate, if you had a '0' setting that turns it off altogether, so for someone who is a purist and prefers not to have 'cheats,' the temptation isn't there.

Do you think that's doable?

**Comment by rdanbrook** [comment]
It's doable but doesn't make a lot of sense when you can simply change the key mappings to disable those buttons, or just not press the turbo buttons if you're that pedantic about it ;). Consider your controller to be an NES Max and then it's not "cheating" anymore since it's the same as an official controller.

I'll be unavailable for the next week, so nothing will change by my hand for at least that long.
