### ISSUE TITLE
glcore and blargg ntsc filter crash nestopia libretro core.

### ISSUE THREAD

**Issue by crocket** [libretro/nestopia#41]
With gl video driver, blargg ntsc filter doesn't crash nestopia libretro core.

I couldn't find anything useful in the log.

GPU // AMD HD6450

```
export MESA_GL_VERSION_OVERRIDE=4.5CORE
export MESA_GLSL_VERSION_OVERRIDE=450
```

**Comment by carmiker** [comment]
No longer an issue.
