### ISSUE TITLE
Nestopia core issue with Holy Diver (JP)

### ISSUE THREAD

**Issue by andrewlxer** [libretro/nestopia#41]
When running Holy Diver (JP), the first level exhibits incorrect sprites being rendered.  It's quite obvious at the bottom of the tree on the first screen.  I first ran into the issue on RetroPie, but reproduced on x86-64 with a custom build as well.

Building Nestopia-UE standalone from the same codebase works fine, so it has something to do with the libretro integration causing the issue.  I have rolled back all the way to August without finding a working version, so presumably it's been broken for a while.

On a side note, I also see completely unlocked framerate when running libretro+Nestopia, as in the emulation runs far too quickly.  I do not see this on Nestopia standalone, or RetroPie (although perhaps it's just limited by the slow CPU).  Is this a settings issue?

**Comment by retro-wertz** [comment]
which do you mean? i cant seem to see difference 
(standalone nestopia at right, zoomed since it captures ingame ss at native res)
![holy diver](https://cloud.githubusercontent.com/assets/23315382/20460535/1aa3b2a4-af21-11e6-847a-77c67968b416.jpg)

**Comment by andrewlxer** [comment]
Odd, that doesn't match what I see on RetroPie or Nestopia+RetroArch (as of most recent commit).  I see blue blocks extending down from the top of the screen, nothing subtle.

Are you on latest git commit for Nestopia and Retroarch?  Platform?

**Comment by retro-wertz** [comment]
latest nestopia_libretro, ra is d1ad845

**Comment by andrewlxer** [comment]
For reference, here is what I see with a fresh build on Ubuntu 16.10:

![holydiver](https://cloud.githubusercontent.com/assets/23608739/20460654/4190e2e2-ae9f-11e6-99b3-7ca649907bf5.png)

vs Nestopia Standalone from the same checkout:

![holydiver2](https://cloud.githubusercontent.com/assets/23608739/20460683/ff3455d6-ae9f-11e6-8dc0-a7df3054ad1e.png)

**Comment by retro-wertz** [comment]
i do not have ubuntu to test on, but ill check lakka- could that possibly be a gpu driver issue?

**Comment by andrewlxer** [comment]
Figured it out, when running from Retroarch I was missing NstDatabase.xml.  With that included, everything is fine.  I suspect RetroPie doesn't include this file and hence the compatibility issues on their side.  Closing this issue out.
