### ISSUE TITLE
Save/load state nondeterminism

### ISSUE THREAD

**Issue by GregorR** [libretro/nestopia#43]
In trying to get Netplay working with every core, I've discovered that the Nestopia core's savestates are subtly nondeterministic. Something is getting set differently in loading states than it would be if the state had arisen naturally, although both seem to continue down plausible—but distinct—execution paths. After a fair bit of poking I'm yet to find anything that differs, though.

I'm really unsure what's breaking, so I'm wondering if anyone more familiar with Nestopia is willing to lend me a hand. I have some resources that could help, such as sequences of per-frame save states that diverge; problem is, of course, whatever is going wrong is something that _isn't_ saved, so I'm not sure whether the states would help. If you're on Linux or another system that supports network delay simulation it's easy enough to replicate the failure using RetroArch's netplay and I could give some tips there too.

**Comment by rdanbrook** [comment]
Should be resolved by this: https://github.com/0ldsk00l/nestopia/pull/301
