### ISSUE TITLE
Lightgun mode has no useable controls.

### ISSUE THREAD

**Issue by Bitwolfies** [libretro/nestopia#45]
Setting nestopa to use the lightgun input setting fails to accept any trigger input due to it not actually looking for any lightgun buttons.

![RetroArch Screenshot 2021 12 13 - 17 53 22 49](https://user-images.githubusercontent.com/65789901/145918513-9d819a2b-e6bc-43d2-8614-283797e00b99.png)
![RetroArch Screenshot 2021 12 13 - 17 53 57 85](https://user-images.githubusercontent.com/65789901/145918545-c9c0b444-16e0-4c49-8e8b-73ed9d13c4d5.png)

**Comment by keithbowes** [comment]
Well, most peripherals (including the Zapper) are on port 2 (some are on ports 3 and 4), but I don't know what you'd need to set to get a lightgun to work (I personally just use my laptop's trackpad, which granted is significantly easier than using a real Zapper).

My recommendations:
1. Check to see if there's a crosshair.  If there's no crosshair, the database doesn't recognize the game as having a Zapper peripheral and you must change that manually (in Port 2 Controls, change the value of *Device Type* from *Auto* to *Zapper*).
2. Does it work with other NES cores?  (As far as I know, FCEUmm is the only other NES core that uses the lightgun API for its Zapper; Mesen uses only the pointer API.)  If not, it might be RetroArch not correctly relaying the lightgun position and button(s) pressed to the core.
