### ISSUE TITLE
Incorrect 1:1 Pixel Aspect Ratio causes scaling artifacts

### ISSUE THREAD

**Issue by westonlast** [libretro/nestopia#47]
All aspect ratios are affected if 1:1 PAR is incorrect.  Notice the scaling artifact shimmer during vertical motion in this case.

I'm not sure if the NES can change resolution dynamically like other consoles, but if it does, RETRO_ENVIRONMENT_SET_GEOMETRY should be used to notify libretro.

**Comment by Monroe88** [comment]
I'm not seeing any problem here. 1:1 PAR + Integer Scale enabled results in perfectly square pixels regardless of overscan settings.

[240pee-170203-173839.png](https://cloud.githubusercontent.com/assets/4119107/22612723/2319fc2a-ea38-11e6-8b34-0552d14fbaf0.png)

**Comment by westonlast** [comment]
Ugh, apparently Integer Scale isn't shared between cores.  Thought I checked.  At least it works, thanks.
