### ISSUE TITLE
error helpme

### ISSUE THREAD

**Issue by jose89fcb** [libretro/nestopia#49]
Hello very good, I am trying to compile the emulator but I have many errors, could someone help me

Here I leave a capture
<img src="https://i.imgur.com/k4fARmP.png">

thank you

**Comment by keithbowes** [comment]
Are you sure this is about the libretro core and not the [standalone program](https://github.com/0ldsk00l/nestopia)?  I don't see the file NstDirect2D.hpp in the libretro core.
