### ISSUE TITLE
some japanese games not working

### ISSUE THREAD

**Issue by bigboo3000** [libretro/nestopia#50]
Hi
The following games are not working at all in libretro_nestopia, they work in fceumm;
Akumajou Special - Boku Dracula-kun (Japan)
Contra (Japan)
Crisis Force (Japan)
Ganbare Goemon 2 (Japan)
Getsu Fuuma Den (Japan)
Wai Wai World 2 - SOS!! Paseri Jou (Japan)

This one works but graphics have many glitches:
Holy Diver (Japan)

I use roms from latest no-intro dat, with or without ips patch translation the result is the same.

**Comment by hizzlekizzle** [comment]
You need to have [NstDatabase.xml](https://raw.githubusercontent.com/libretro/nestopia/master/NstDatabase.xml) in your system/BIOS directory.

**Comment by bigboo3000** [comment]
Oh thank you I didn't know this file was needed.

But there is another problem now, softpatching still doesn't work with the same games.

**Comment by bigboo3000** [comment]
I solved the problem with adding crc32 and sha1 of hardpatched games to the database, if you want to add them I've pasted the code here:

`    <game>
        <cartridge system="Famicom" dump="unknown" crc="CFE0FF2C" sha1="93F4FF878BF00178190BB864DD73F850C18DD399">
            <board type="KONAMI-VRC-4" mapper="23">
                <prg size="128k" />
                <chr size="128k" />
                <chip type="Konami VRC IV">
                    <pin number="3" function="PRG A3" />
                    <pin number="4" function="PRG A2" />
                </chip>
            </board>
        </cartridge>
    </game>
	<game>
        <cartridge system="Famicom" dump="unknown" crc="E1D20375" sha1="56F90154D82ED2E8A3C219FBA0C2E70CD3E8DE1D">
            <board type="KONAMI-VRC-2" mapper="23">
                <prg size="128k" />
                <chr size="128k" />
                <chip type="Konami VRC II">
                    <pin number="3" function="PRG A1" />
                    <pin number="4" function="PRG A0" />
                    <pin number="21" function="CHR A10" />
                    <pin number="22" function="CHR A16" />
                    <pin number="23" function="CHR A11" />
                    <pin number="24" function="CHR A13" />
                    <pin number="25" function="CHR A14" />
                    <pin number="26" function="CHR A12" />
                    <pin number="27" function="CHR A15" />
                    <pin number="28" function="NC" />
                </chip>
            </board>
        </cartridge>
    </game>
    <game>
        <cartridge system="Famicom" dump="ok" crc="B2E81F64" sha1="9FB9615A18A1A228DA3713AA382F33BB08F73FA2">
            <board type="KONAMI-VRC-4" mapper="23">
                <prg size="128k" />
                <chr size="128k" />
                <wram size="2k" />
                <chip type="Konami VRC IV">
                    <pin number="3" function="PRG A3" />
                    <pin number="4" function="PRG A2" />
                </chip>
            </board>
        </cartridge>
    </game>
    <game>
        <cartridge system="Famicom" dump="ok" crc="8A1309F7" sha1="568756853A209A7545189843D84DD27585CE55D5">
            <board type="KONAMI-VRC-2" mapper="23">
                <prg size="128k" />
                <chr size="128k" />
                <chip type="Konami VRC II">
                    <pin number="3" function="PRG A1" />
                    <pin number="4" function="PRG A0" />
                    <pin number="21" function="CHR A10" />
                    <pin number="22" function="CHR A16" />
                    <pin number="23" function="CHR A11" />
                    <pin number="24" function="CHR A13" />
                    <pin number="25" function="CHR A14" />
                    <pin number="26" function="CHR A12" />
                    <pin number="27" function="CHR A15" />
                    <pin number="28" function="NC" />
                </chip>
            </board>
        </cartridge>
    </game>
    <game>
        <cartridge system="Famicom" dump="ok" crc="FB847D1A" sha1="BD54D8D2D55C066AF8B98EADDE956CC28235D293">
            <board type="KONAMI-VRC-2" mapper="23">
                <prg size="128k" />
                <chr size="128k" />
                <chip type="Konami VRC II">
                    <pin number="3" function="PRG A1" />
                    <pin number="4" function="PRG A0" />
                    <pin number="21" function="CHR A10" />
                    <pin number="22" function="CHR A16" />
                    <pin number="23" function="CHR A11" />
                    <pin number="24" function="CHR A13" />
                    <pin number="25" function="CHR A14" />
                    <pin number="26" function="CHR A12" />
                    <pin number="27" function="CHR A15" />
                    <pin number="28" function="NC" />
                </chip>
            </board>
        </cartridge>
    </game>
    <game>
        <cartridge system="Famicom" dump="unknown" crc="564F7161" sha1="B04A18F9D7DE352A2862ACA18F6AA81F78A672DF">
            <board type="IREM-HOLYDIVER" mapper="78">
                <prg size="128k" />
                <chr size="128k" />
            </board>
        </cartridge>
    </game>
    <game>
        <cartridge system="Famicom" dump="ok" crc="82D05506" sha1="F26AD865EEA7545043E5C3DBD96A99FA2F1F3C61">
            <board type="KONAMI-VRC-4" mapper="21">
                <prg size="256k" />
                <chr size="128k" />
                <chip type="Konami VRC IV">
                    <pin number="3" function="PRG A2" />
                    <pin number="4" function="PRG A1" />
                </chip>
            </board>
        </cartridge>
    </game>`

**Comment by hizzlekizzle** [comment]
Ah, smart!

**Comment by Yabuato** [comment]
Hi,mind send me your modded xml?I can't get games working by pasting your code.
