### ISSUE TITLE
Zapper games issues

### ISSUE THREAD

**Issue by Tatsuya79** [libretro/nestopia#53]
Zapper games like Duck Hunt crash on close content or exit.
No problem with gamepad only games.

Backtrace: http://pastebin.com/qVbdMHvs

It can also crash on window/fullscreen change randomly:

Backtrace: http://pastebin.com/rXa7e6Xm

Retroarch 1.5 win7 x64 nvidia 770 GTX.
Someone confirmed it on win32 too.

**Comment by Tatsuya79** [comment]
It crashes as soon as you cross the border of the screen on an old retroarch build prior to this bug:
https://github.com/libretro/RetroArch/issues/3408

But it didn't crash on exit.
So no need to bother with that before a fix is made at retroarch level probably.

Defining a limit range for the mouse will be needed though.

**Comment by Tatsuya79** [comment]
Retroarch isn't crashing any more when closing Nestopia after playing a zapper game on today's core build. (with today mouse fixes)
The behaviour is still not ideal: screen has "sticky corners".
When the mouse pointer reach a side of the screen, the movement you make past that border has to be made the same amount in the opposite direction before the cursor can move again.

Retroarch 1.6 Win7 x64 dinput

**Comment by markwkidd** [comment]
I have this "sticky corners" phenomenon as well. @casdevel is the most expert person I know on mice in RetroArch.

Even though I think this is not related to some of the projects casdevel has been working on, maybe they will have some insight.

**Comment by casdevel** [comment]
@Tatsuya79 I haven't checked Nestopia core sources, but pointer behavior implies that core don't handle mouse move properly.

Fix should be pretty straightforward, but these days I'm pretty busy so I can't help right now...

In the meantime, if someone else wanna try fix this issue:
After polling mouse state and updating pointer position, core just needs to clamp pointer position to core video geometry. So, in theory, only clamping should be added.

**Comment by markwkidd** [comment]
It might be relevant to look at this commit as well: https://github.com/rdanbrook/nestopia/pull/228

> Previously there were no checks at all for the bounds where the crosshair was drawn, so it could be drawn outside of the allocated video_buffer. Most notably this bug caused nestopia core to crash when you were closing it, if the crosshair was located at the bottom or the top of the screen. Actually that was usually the case (for me at least) in case you hadn't moved your mouse at all, since by default the crosshair is placed on the top left corner.

@arakerlu based on your previous Nestopia crosshair work, are you familiar with this similar bug? The screen corners are inappropriately 'sticky' to the crosshair as the mouse cursor passes outsdide the Nestopia display boundaries.
