### ISSUE TITLE
Core Details not information about NstDatabase.xml

### ISSUE THREAD

**Issue by Augusto7743** [libretro/nestopia#57]
Nestopia core need NstDatabase.xml in "system firmware" path.
In Core \ Manage Cores not have information about NstDatabase.xml.
The user need understand NstDatabase.xml is required for load games.
That information need to be added in core.

**Comment by keithbowes** [comment]
NstDatabase.xml isn't needed anymore.  Anywhere that mentions that it's needed is outdated.

**Comment by Augusto7743** [comment]
Thanks for replying.
Information about Nestopia core need to be updated in
https://docs.libretro.com/guides/navigating
I not have access to remove that wrong information.

**Comment by hizzlekizzle** [comment]
Anyone can update the docs by making a PR against https://github.com/libretro/docs

**Comment by Augusto7743** [comment]
Thanks for your reply.
