### ISSUE TITLE
Zapper input on pointer mode resets to center when horizontally is out of bounds

### ISSUE THREAD

**Issue by sokairyk** [libretro/nestopia#58]
I tried to set my Zapper to be used as pointer instead of mouse to avoid changing the mouse sensitivity each time. I have a monitor with 1920x1080 resolution and because of the 4:3 aspect ratio when the cursor moves out of horizontal bounds of the rendered video, it resets to the center of the screen. If I change following option from: Video -> Scaling -> Core Provided to Video -> Scaling -> 16:9 then I don't have this issue but the video is streched. Also using mouse instead of pointer doesn't have this behavior, but I really prefer the pointer option.

**Comment by keithbowes** [comment]
I suppose it depends on the frontend you're using and on which platform you're using it.  Using the latest version of RetroArch on my Linux computer with a touchpad, my results are:
* In Wayland: Works perfectly with "pointer", but the crosshair doesn't move with "mouse".
* In X and KMS: Works with both "mouse" and "pointer"; the difference is that firing is done by using the buttons with "mouse" but by lifting your finger off the touchpad with "pointer".
* The Windows version under WINE: I'm seeing the behavior you're describing, so I suppose you're using Windows.
