### ISSUE TITLE
FCEUX-like NES Overclocking [$50]

### ISSUE THREAD

**Issue by saftle** [libretro/nestopia#59]
Here is a great side-by-side demonstration of overclocking in standalone FCEUX:

https://www.youtube.com/watch?v=VzQE4pLjhg4

Related to feature request: https://github.com/libretro/nestopia/issues/26

Reopened to create a bounty (for the hell of it!).

**Comment by rdanbrook** [comment]
Good luck to anyone who wishes to attempt this. It will be accepted only if it does not break the original functionality of the core; the overclocking absolutely must be optional.

**Comment by saftle** [comment]
@rdanbrook I agree 100%.

For those willing to get their hands dirty, I found the original nesdev forum thread discussing the feature, and the sourceforge overclocking commit that was added to FCEUX:

https://forums.nesdev.com/viewtopic.php?f=3&t=12823
https://sourceforge.net/p/fceultra/bugs/701/

**Comment by meepingsnesroms** [comment]
This is about 30% done, it is much harder for this core than fceumm since there is a strict syntax and there is no scanline counter they are lumped into the cpu cycle counter.

**Comment by rdanbrook** [comment]
Feel free to show some of what you've done already, I wouldn't mind seeing the approach you're taking.

**Comment by meepingsnesroms** [comment]
It is on my fork on github.
[Here](https://github.com/meepingsnesroms/nestopia)

Any help would be appreciated, I am not going for the bounty anyway since I feel that would be a conflict of interest.

**Comment by saftle** [comment]
Oh exciting stuff! I read somewhere that Mesen has a better form of overclocking than FCEUX after I had made this bounty. Is it similar to FCEUX's method, Mesen's or is it a unique take on it?

**Comment by meepingsnesroms** [comment]
I dont know yet, I have only implemented the toggles and audio safety option.

I will try to find the best option available and use that.

I just got back from a 7 day vacation so that is why nothing has happened recently with this.

**Comment by saftle** [comment]
I see that @rdanbrook committed the changes. Thank you!

Also, thanks again so much for your work @meepingsnesroms. I can't wait to try it out.

Regarding transferring the bounty to another issue, it appears adolfobenjaminv (Reddit: https://www.reddit.com/user/adolfobenjaminv | Discord: adolfobenjaminv#5362) wanted to create a bounty for a j2me libretro core. He created a reddit thread here: https://www.reddit.com/r/emulation/comments/70rfye/anyone_interested_to_start_a_bounty_for_a_j2me/.

It appears that there is also a group working on a j2me libretro core as discussed in the reddit thread. 

If you want me to proceed and transfer it to a j2me related issue, I can do so as soon as an issue exists for it. I'm unfamiliar with j2me emulation, so as soon as either you or adolfobenjaminv create an issue, I can get in touch with the people at bountysource to see if I can transfer the funds. You could create the issue under https://github.com/libretro/libretro-meta (thanks to a suggestion by @bparker06 ).

Otherwise, please let me know how to proceed :)

**Comment by meepingsnesroms** [comment]
I made the new issue here:
[J2ME Emulator](https://github.com/libretro/libretro-meta/issues/100)

This issue should be closed now.
