### ISSUE TITLE
nestopia_libretro doesn't save input_libretro_device

### ISSUE THREAD

**Issue by kaylh** [libretro/nestopia#59]
Hello,

I seems that nestopia libretro core doesn't save or load values at `input_libretro_device_*` in `retroarch.cfg`.

e.g If I want to use the zapper as emulated device, it works when I select it in the menu, but the next time when I run retroarch with nestopia, it always revert back to auto.

All others settings are saved, but not those related to inputs.

I use retroarch 1.10.3 Windows 64bit with the latest build of nestopia_libretro available on the buildbot.

**Comment by keithbowes** [comment]
Does any core do that?  They don't for me.  You can manually save the remaps to preserve controller settings but it never seems to be automatic.
