### ISSUE TITLE
Sound mode mono only output for left speaker

### ISSUE THREAD

**Issue by Augusto7743** [libretro/nestopia#66]
Hello.
Using Nestopia UE core 1.52 dd78611.
If Audio Output is Mono the sound output is only for left speaker.
If selecting Stereo both left and right speaker have sound output.

The correct is Mono being for both left and right speaker ? or Stereo not split sounds fx for each speaker side and does sound output with exact same sound in both left and right speaker ?

Thanks for reading.
Have an nice week.

**Comment by hizzlekizzle** [comment]
The NES only has 2 RCA jacks: one for video and one for mono audio.
![image](https://user-images.githubusercontent.com/2805586/215509131-fd3bb688-ea5f-480b-bcee-f4afe6d4a17f.png)
So, it should only come out of one channel. The faux stereo mode may do some heuristic channel separation or it may just dupe out the mono signal to the other channel, dunno.

**Comment by Augusto7743** [comment]
Nestopia UE is doing wrong.
If selecting Sound Mono need to do the same sound in both left and right speakers.
If selecting Sound Stereo does an virtual stereo for both left and right speakers.

**Comment by Augusto7743** [comment]
Thanks.
