### ISSUE TITLE
Segfault on RPi3

### ISSUE THREAD

**Issue by Kivutar** [libretro/nestopia#69]
Reported here https://github.com/libretro/Lakka-LibreELEC/issues/240

With version https://github.com/libretro/nestopia/commit/071f04ea1ca54b50d02b4da7cce3cebe863a78ca

I can't get a backtrace:

```
(gdb) r
Starting program: /usr/bin/retroarch 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[New Thread 0x754e73f0 (LWP 585)]
[New Thread 0x74c663f0 (LWP 586)]
[New Thread 0x742ff3f0 (LWP 587)]
[New Thread 0x738ff3f0 (LWP 588)]
[New Thread 0x730ff3f0 (LWP 589)]
[New Thread 0x728ff3f0 (LWP 590)]
[New Thread 0x71cff3f0 (LWP 591)]
[Thread 0x74c663f0 (LWP 586) exited]
[Thread 0x71cff3f0 (LWP 591) exited]
[Thread 0x754e73f0 (LWP 585) exited]
[New Thread 0x754e73f0 (LWP 592)]

Thread 1 "retroarch" received signal SIGSEGV, Segmentation fault.
0x76edf3e0 in memcmp () from /usr/lib/libarmmem.so
(gdb) bt
#0  0x76edf3e0 in memcmp () from /usr/lib/libarmmem.so
#1  0x00000000 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
```
And I can't bisect easily.

**Comment by simias** [comment]
memcmp is heavily optimized ASM and (probably) reuses LR to store data, hence messing up the call stack. I've had this problem in the past with memset on ARM.

I'd recommend looking up the particular implementation of this memcmp, figure out where it pushes LR on the stack and use that to figure out where it messes up. Alternatively you could try using an LD_PRELOAD trick to lead a standard C implementation of the function which won't have this issue.
