### ISSUE TITLE
Option System Region ( NTSC and Famicom ) are related only to refresh rate ?

### ISSUE THREAD

**Issue by Augusto7743** [libretro/nestopia#72]
Hello.
The option System Region only change the refresh rate FPS settings between models or does other actions ?
Thanks for reading.

**Comment by carmiker** [comment]
It affects refresh rate and addon peripherals, as the Famicom used an expansion port and the NES used the regular controller ports in these cases. This is not relevant right now in the libretro port, but will be once more peripherals are supported.

**Comment by Augusto7743** [comment]
Thanks for your reply.
