### ISSUE TITLE
Super Gun (USA) (Unl)

### ISSUE THREAD

**Issue by Cibomatto2002** [libretro/nestopia#78]
Super Gun (USA) (Unl) will only work in Mesen

MD5: 16D8999C8B35C509FC6DD3568C0CEF93

**Comment by Cibomatto2002** [comment]
found out it needs mapper 81 to run.

https://forums.nesdev.org/viewtopic.php?t=16412

**Comment by keithbowes** [comment]
Mapper 81 has been added upstream (https://gitlab.com/jgemu/nestopia/-/commit/5ac45d90d8e1c1ca7a8545df45c17bf9288ba2c9), so I guess it's only a matter of time until the code gets merged with the libretro port (that usually happens when there's a new upstream version, e.g. 1.53.0).
