### ISSUE TITLE
Famicom Disk System .sav Files Go in Browser Directory Instead of Savefile Directory

### ISSUE THREAD

**Issue by Awakened0** [libretro/nestopia#8]
Or they end up in your extraction directory if you have one set. NES or cartridge based Famicom game's save files go in the save directory as expected.

**Comment by fr500** [comment]
hmmm I guess it's not using the save interface for this, it should be easy to fix using retro_environment_get_save_directory

**Comment by Awakened0** [comment]
Fixed as of 27cb3a968a58b6ddcf32ca21b92167ffbd601791.

Thanks!

**Comment by Awakened0** [comment]
This doesn't work right with save file sorting enabled. It will read previously made FDS saves from savefolder\Nestopia, but it writes them to the root of the save folder. I've turned off save folder sorting for this core and set the save folder manually using an override for now.

**Comment by fr500** [comment]
This is really odd..

**Comment by Awakened0** [comment]
Here's a log: http://pastebin.com/FZ7Q0HNu

The relevant lines seem to be:

RetroArch: event_save_files: Saving RAM type #0 to ".\Save\Nestopia\Nazo no Murasamejou (Japan) [En by Spinner 8 v1.1] (~The Mysterious Murasame Castle).srm".
RetroArch: event_save_files: Saving RAM type #1 to ".\Save\Nestopia\Nazo no Murasamejou (Japan) [En by Spinner 8 v1.1] (~The Mysterious Murasame Castle).rtc".
RetroArch: rarch_log_libretro: [libretro INFO] :: Want to save FDS sav to: .\Save\\Nazo no Murasamejou (Japan) [En by Spinner 8 v1.1] (~The Mysterious Murasame Castle).sav

With the save sort off and the path set manually in the override, it looks like this:

RetroArch: event_save_files: Saving RAM type #0 to ".\Save\Nestopia\Nazo no Murasamejou (Japan) [En by Spinner 8 v1.1] (~The Mysterious Murasame Castle).srm".
RetroArch: event_save_files: Saving RAM type #1 to ".\Save\Nestopia\Nazo no Murasamejou (Japan) [En by Spinner 8 v1.1] (~The Mysterious Murasame Castle).rtc".
RetroArch: rarch_log_libretro: [libretro INFO] :: Want to save FDS sav to: .\Save\Nestopia\\Nazo no Murasamejou (Japan) [En by Spinner 8 v1.1] (~The Mysterious Murasame Castle).sav
