### ISSUE TITLE
Kid Dracula translation not working (and other translated games using that mapper)

### ISSUE THREAD

**Issue by riggles1** [libretro/nestopia#82]
As stated in here:

https://forums.libretro.com/t/kid-dracula-english-translation-doesnt-work-in-nestopia-core/29395

Would love to see this fixed as nestopia's audio adjustments are excellent.

**Comment by carmiker** [comment]
The ideal solution is for ROM hackers to set the NES 2.0 submapper field when hacking VRC2/4 ROMs. This game is VRC4e, or mapper 23.2. You can make the game work by setting the submapper to `2` yourself, or adding an entry to NstDatabase.xml. I prefer to avoid adding hacks and translations to the game database -- the hack can be updated, and this will break the database entry and potentially any heuristics based on the ROM content itself. However, it seems some other emulators have used this approach, so I may consider it in this case.

Reference: https://www.nesdev.org/wiki/NES_2.0_submappers#021_/_023_/_025:_1,_2_VRC4
