### ISSUE TITLE
Koko Adventure (Korea) (En) (Unl) [graphical glitches]

### ISSUE THREAD

**Issue by Cibomatto2002** [libretro/nestopia#85]
This is a good rom it passed no - into. It works on other emulator just fine just not on nestopia :(

![Capture3-14-2024-9 59 27 PM](https://github.com/libretro/nestopia/assets/21169038/f5a42806-29db-45a7-be41-822d57716ab8)

**Comment by carmiker** [comment]
Thanks for the report. It appears to be an issue with nametable mirroring. I will get it fixed before the upcoming release tag.

**Comment by Cibomatto2002** [comment]
Can you look at the other game I post it had bugs to. Policeman (Spain) (En) (Gluk Video) (Unl) [graphical glitches

**Comment by carmiker** [comment]
Policeman is already fixed in the upstream repo. I am hoping to tag a new release soon, and when I do, I will merge everything into this repo.
