### ISSUE TITLE
Mute ultrasonic frequencies on the triangle channel. Reduce popping sounds on the DMC channel

### ISSUE THREAD

**Issue by Cibomatto2002** [libretro/nestopia#86]
This would be nice because games like Jackal has this popping sounds in the music there are other games that has it to Mesen has these options.

Mute ultrasonic frequencies on the triangle channel: This option mutes the triangle channel under certain conditions, which prevents it from causing popping sounds.

Reduce popping sounds on the DMC channel: Similar to the previous option, but for the DMC channel – this option prevents games from changing the output of the DMC channel too abruptly, which often causes popping sounds.

https://www.mesen.ca/docs/configuration/audio.html

**Comment by carmiker** [comment]
Testing on Nestopia, HighNES (my in-development extremely high accuracy NES emulator) and real hardware, I believe Nestopia is already doing this sufficiently. It already basically sounds like Mesen using the above mentioned options. That said, the next release of Nestopia will have some new APU work done, so I will think about this while I am working on the changes. Real hardware (in this test, an AV Famicom) sounds more like HighNES, so the game just inherently pops.

Nestopia: https://files.catbox.moe/bpujhx.ogg
HighNES: https://files.catbox.moe/xgevdy.ogg
