### ISSUE TITLE
[Question] Sound samples support

### ISSUE THREAD

**Issue by cmitu** [libretro/nestopia#86]
Hello,

 I'm wandering if the core supports sound samples, like the standalone Nestopie-UE does, for the list of games listed as supporting it (for instance **Moero!! Pro Yakyuu**, using the `moepro.zip` sample with the .wav files).

 I've tried adding the samples .zip in the same folder as the XML database, or in a `samples` subfolder, but they don't seem to get loaded.

 I'm using the latest version (1.49 WIP) on linux, with RetroArch 1.7.3.

**Comment by rdanbrook** [comment]
To be honest with you, I didn't know such a feature existed in the first place! There are a lot of obscure features in this codebase apparently, and I've been working on it for many years now without noticing anything about samples. I'll do more research on it.

**Comment by rdanbrook** [comment]
Just an update, I have looked into this and it appears I need to write a fair bit of extra code to read the .wav data into the emulator core. It's not as simple as loading a file, and the original implementation was Windows-specific. I am going to attempt this, hopefully it goes smoothly.

**Comment by cmitu** [comment]
Thank you for looking into this. The issue is not a request or a bug report, it was more of a question - but if you need additional testing let me know.

**Comment by rdanbrook** [comment]
OK, I just finished adding this feature. It works with all 5 games that use samples. For the cross-platform port you can use a .zip but for libretro you'll need to extract the .zip into a directory. It will be [system directory]/nestopia/samples/[gamename]. For example, ~/.config/retroarch/system/nestopia/samples/moepro88 would need to contain the extracted sample files for Moero!! Pro Yakyuu '88 - Ketteiban.
