### ISSUE TITLE
Please add MAME nes roms set compatibility

### ISSUE THREAD

**Issue by legluondunet** [libretro/nestopia#88]
Hello,

could you add  MAME Nes  roms set compatibility? 

MAME Nes roms extension are not .nes, but prg or chr
For example:
aladdin.zip contains  a file named "pal-aj-0 prg"
bombman.zip contain two files named "nes-bm-0 chr" and "nes-bm-0 prg"

Thank you for your help.

**Comment by rdanbrook** [comment]
I'm aware that this ROM format exists, but adding it to this codebase is non-trivial. I'll accept pull requests if anyone else wants to take this on.
