### ISSUE TITLE
fullscreen not in monitor native resolution

### ISSUE THREAD

**Issue by SteegHobland** [libretro/nestopia#89]
I'm using Nestopia Undead Edition 1.45 on Linux Mint 17.3 Cinnamon 32-bit.

When I switch to fullscreen, instead of staying at my displays normal, native resolution, it switches to another, undesired, screen resolution, which does not match the aspect ratio of my screen. A resolution such as 640x480, for example. The screen has a ratio of 16:10, and the image does not appear to be scaled to correct for the aspect ratio difference, but rather appears to assume a 4:3 aspect ratio, and is distorted.

I would like the resolution setting of my display to never change from its native resolution. In this case, 1440x900.

Another somewhat acceptable alternative would be a way to set the display's actual aspect ratio, and for the displayed image to be scaled to compensate for that, to avoid undesirable image distortion, rather than assuming the ratio based on the current screen resolution.

**Comment by fr500** [comment]
This repo is for the libretro core, not for the standalone application.

**Comment by rdanbrook** [comment]
On top of that, you are using a version from like 4 or 5 years ago. Update your software stack and try again.

**Comment by SteegHobland** [comment]
Oh, how silly of me. I didn't realize I was in the wrong place. Sorry about that.
