### ISSUE TITLE
No notifications when changing diskette for Famicom Disk System

### ISSUE THREAD

**Issue by KamiLordus** [libretro/nestopia#91]
Please add text notifications when changing a diskette for the Famicon Disk system.
Without text notifications, it is difficult to change a diskette and easy to make a mistake.
This is how it looks in the case of the FCEUmm core:

![Bubble Bobble (Japan)-241119-113234](https://github.com/user-attachments/assets/c61e2f3f-2095-49fb-9529-016359df2da5)

**Comment by carmiker** [comment]
Yes, this is a needed improvement. The FDS disk switching is generally dodgy and needs some work.

**Comment by carmiker** [comment]
Done!

**Comment by KamiLordus** [comment]
Now it works great. Thanks a lot.
