### ISSUE TITLE
Elite from the Elite Homepage doesn't work.

### ISSUE THREAD

**Issue by Luraktinus** [libretro/nestopia#93]
I wanted to use this version of elite that's non-copyrighted by Nintendo and that's legally and free to download on the Elite homepage, made by the developer.
http://www.elitehomepage.org

The screen has bugs and it's cut off
![Screenshot_20190606-125447](https://user-images.githubusercontent.com/33608674/59027843-5bcb6000-885a-11e9-89bd-20921554c9d9.png)

**Comment by retro-wertz** [comment]
im sure that this problem has been answered when this was asked over at discord - set the game to run in PAL
